import fs from 'node:fs/promises';
const OUT=new URL('../docs/data/tracker.json',import.meta.url);const now=new Date();
const urls={oira:'https://www.reginfo.gov/public/do/eoDetails?rrid=1457213',meetings:'https://www.reginfo.gov/public/do/eom12866SearchResults?pubId=202510&rin=2120-AL82&viewRule=true&viewall=Y&view=yes',federalRegister:'https://www.federalregister.gov/api/v1/documents.json?per_page=50&order=newest&conditions%5Bterm%5D=2120-AL82'};
async function get(name,url){try{const r=await fetch(url,{headers:{'user-agent':'Metal-Raptor-Part-108-Tracker/1.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return{name,ok:true,body:await r.text(),detail:`HTTP ${r.status}`,url}}catch(e){return{name,ok:false,body:'',detail:String(e.message||e),url}}}
const [oira,meet,fr]=await Promise.all(Object.entries(urls).map(([n,u])=>get(n,u)));let previous={};try{previous=JSON.parse(await fs.readFile(OUT,'utf8'))}catch{}
const received='2026-07-10';const days=Math.max(0,Math.floor((now-new Date(received+'T00:00:00Z'))/86400000));
const pending=oira.ok?/Pending/i.test(oira.body):previous.oiraPending??true;const stage=pending?'Final rule under OIRA review':(previous.stage||'OIRA status requires verification');
const meetingRows=[...meet.body.matchAll(/href="([^"]*viewEO12866Meeting[^"]*)"[^>]*>\s*(\d{2}\/\d{2}\/\d{4})\s+([^<]+)</gi)].map(m=>({date:m[2],dateDisplay:`${m[2]} ${m[3].trim()}`,requestor:'OIRA meeting record',url:new URL(m[1].replace(/&amp;/g,'&'),'https://www.reginfo.gov').href,status:'Posted'}));
const count=meet.ok?meetingRows.length:previous.meetingCount??0;
let docs=[];if(fr.ok){try{docs=(JSON.parse(fr.body).results||[]).filter(d=>/beyond visual line of sight operations/i.test(d.title||''))}catch{}}const latest=docs[0];const latestDocument=latest?{title:latest.title,number:latest.document_number,publicationDate:latest.publication_date,type:latest.type,action:latest.action,url:latest.html_url}:previous.latestDocument||{};
const finalRulePublished=docs.some(d=>/rule/i.test(d.type||'')&&!/proposed/i.test(d.type||'')&&/beyond visual line of sight operations/i.test(d.title||''));
const changes=[];if(!previous.lastChecked)changes.push('Initial verified baseline loaded.');else{if(previous.stage!==stage)changes.push(`Stage changed from “${previous.stage}” to “${stage}”.`);if(previous.meetingCount!==count)changes.push(`OIRA meeting count changed from ${previous.meetingCount} to ${count}.`);if(previous.latestDocument?.number!==latestDocument.number)changes.push(`Latest Federal Register document changed to ${latestDocument.number}.`);if(!changes.length)changes.push('No material lifecycle change detected since the prior snapshot.');}
const sourceHealth=[oira,meet,fr].map(x=>({name:x.name==='oira'?'OIRA review record':x.name==='meetings'?'OIRA meeting docket':'Federal Register API',ok:x.ok,checkedAt:now.toISOString(),detail:x.detail,url:x.url}));
const snapshot={stage,overall:finalRulePublished?'Green':'Yellow',oiraPending:pending,oiraReceivedDate:received,daysInOira:days,meetingCount:count,upcomingMeetings:meetingRows.filter(x=>new Date(x.date)>=new Date(now.toDateString())).slice(0,12),latestDocument,finalRulePublished,lastChecked:now.toISOString(),nextAutomaticCheck:new Date(now.getTime()+6*3600000).toISOString(),changes,sourceHealth,stale:sourceHealth.some(x=>!x.ok),interpretationNote:'Automated checks detect official lifecycle events and source changes. Substantive provision analysis remains human-reviewed.',history:[{checkedAt:now.toISOString(),stage,meetingCount:count,latestDocumentNumber:latestDocument.number||null,changes},...(previous.history||[])].slice(0,24)};
await fs.mkdir(new URL('../docs/data/',import.meta.url),{recursive:true});await fs.writeFile(OUT,JSON.stringify(snapshot,null,2)+'\n');console.log(JSON.stringify({stage,count,latest:latestDocument.number,changes,health:sourceHealth.map(x=>[x.name,x.ok])},null,2));
